### ISSUE TITLE
Unable to create a directory in path

### ISSUE THREAD

**Issue by justinbass** [zingale/pyjournal#1]
Directly from the README, executed on OS X Yosemite:

# sudo ./pyjournal/pyjournal.py init nickname path/
ERROR: unable to create a directory in path

**Comment by zingale** [comment]
I think that the docs were a little unclear here -- `path/` should be an existing directory, and the master git repo directory is created inside that.  I clarified that in the README.md, and also tried to have the `init` subcommand make the `path/` if it doesn't exist first, before making the journal repo directories.
